# -*- coding: utf-8 -*-
"""K-Means Clustering

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R0qR_mRwX31-xXohlMISz6t_WIdtoPh7

Import Libraries
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_score

# Ignore warnings
import warnings
warnings.filterwarnings('ignore')

"""Load dataset"""

df = pd.read_csv('/content/Mall_Customers.csv')

# Display first 5 rows
df.head()

"""Basic Data Information"""

print("Dataset Shape:", df.shape)

print("\nColumns:")
print(df.columns)

print("\nDataset Info:")
print(df.info())

print("\nMissing Values:")
print(df.isnull().sum())

print("\nStatistical Summary:")
print(df.describe())



"""Data Visualization"""

# Age Distribution

plt.figure(figsize=(6,4))
sns.histplot(df['Age'], bins=20, kde=True)
plt.title("Age Distribution")
plt.show()

# Annual Income Distribution

plt.figure(figsize=(6,4))
sns.histplot(df['Annual Income (k$)'], bins=20, kde=True)
plt.title("Annual Income Distribution")
plt.show()

# Spending Score Distribution

plt.figure(figsize=(6,4))
sns.histplot(df['Spending Score (1-100)'], bins=20, kde=True)
plt.title("Spending Score Distribution")
plt.show()

"""Select Features For Clustering"""

X = df[['Annual Income (k$)', 'Spending Score (1-100)']]

X.head()

"""Feature Scaling"""

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

print(X_scaled[:5])

"""Find Optimal Number of Clusters (Elbow Method)"""

wcss = []

for i in range(1,11):
    kmeans = KMeans(
        n_clusters=i,
        init='k-means++',
        random_state=42
    )

    kmeans.fit(X_scaled)

    wcss.append(kmeans.inertia_)

# Plot Elbow Curve

plt.figure(figsize=(8,5))
plt.plot(range(1,11), wcss, marker='o')
plt.title('Elbow Method')
plt.xlabel('Number of Clusters')
plt.ylabel('WCSS')
plt.show()

"""Train K-Means Model"""

kmeans = KMeans(
    n_clusters=5,
    init='k-means++',
    random_state=42
)

clusters = kmeans.fit_predict(X_scaled)

clusters

"""Add Cluster Labels"""

df['Cluster'] = clusters

df.head()

"""Visualize Customer Segments"""

plt.figure(figsize=(10,7))

plt.scatter(
    X_scaled[clusters == 0, 0],
    X_scaled[clusters == 0, 1],
    s=80,
    label='Cluster 1'
)

plt.scatter(
    X_scaled[clusters == 1, 0],
    X_scaled[clusters == 1, 1],
    s=80,
    label='Cluster 2'
)

plt.scatter(
    X_scaled[clusters == 2, 0],
    X_scaled[clusters == 2, 1],
    s=80,
    label='Cluster 3'
)

plt.scatter(
    X_scaled[clusters == 3, 0],
    X_scaled[clusters == 3, 1],
    s=80,
    label='Cluster 4'
)

plt.scatter(
    X_scaled[clusters == 4, 0],
    X_scaled[clusters == 4, 1],
    s=80,
    label='Cluster 5'
)

plt.scatter(
    kmeans.cluster_centers_[:,0],
    kmeans.cluster_centers_[:,1],
    s=300,
    c='black',
    marker='X',
    label='Centroids'
)

plt.title('Customer Segmentation using K-Means')
plt.xlabel('Annual Income (Scaled)')
plt.ylabel('Spending Score (Scaled)')
plt.legend()
plt.show()

"""Evaluate Model using Silhouette Score"""

score = silhouette_score(X_scaled, clusters)

print("Silhouette Score:", round(score,3))

"""Analyze Cluster Counts"""

cluster_counts = df['Cluster'].value_counts().sort_index()

print(cluster_counts)

"""Cluster-wise Summary"""

cluster_summary = df.groupby('Cluster')[[
    'Age',
    'Annual Income (k$)',
    'Spending Score (1-100)'
]].mean()

cluster_summary

df.to_csv('Customer_Segmentation_Output.csv', index=False)

print("File saved successfully!")

print(df.head(20))

df.to_csv("Customer_Segmentation_Output.csv", index=False)

sns.pairplot(
    df,
    vars=['Age','Annual Income (k$)','Spending Score (1-100)'],
    hue='Cluster'
)

plt.show()

plt.figure(figsize=(10,6))

sns.scatterplot(
    data=df,
    x='Annual Income (k$)',
    y='Spending Score (1-100)',
    hue='Cluster',
    palette='Set1',
    s=100
)

plt.title("Customer Segmentation")
plt.show()